.cloud-dependencies:init:
  variables:
    MODULE_NAME: cloud-dependencies # 目录
  before_script:
    - export GRADLE_USER_HOME=`pwd`/.gradle
    - cd ${MODULE_NAME}

cloud-dependencies:build:
  extends:
    - .cloud-dependencies:init
  stage: build
  tags:
    - pve
    - docker
  rules:
    - if: '$CI_COMMIT_BRANCH =~ /^standalone*/'
      changes:
        - ${MODULE_NAME}/*.{kts,properties,yml}
        - ${MODULE_NAME}/**/*
  script:
    - gradle build publishAllPublicationsToBjknrtRepository
  cache:
    paths:
      - .gradle/wrapper
      - .gradle/caches
  artifacts:
    when: always
    reports:
      junit: ${MODULE_NAME}/**/build/test-results/test/**/TEST-*.xml