apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
configurations:
  - kustomize-config.yaml
resources:
  - base.yaml
commonAnnotations:
  git/commit: $(IMAGE_TAG)
vars:
  - name: SERVICE_NAME
    objref:
      kind: Service
      name: user-permission-centre
      apiVersion: v1
  - name: NAMESPACE
    objref:
      kind: Service
      name: user-permission-centre
      apiVersion: v1
    fieldref:
      fieldpath: metadata.namespace