server:
  port: 8083
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/web
    username: root
    password: 1234qwer
  cloud:
    nacos:
      config:
        enabled: false
      discovery:
        enabled: false
    discovery:
      enabled: true
      client:
        simple:
          instances:
            hmp-web:
              - uri: "http://127.0.0.1:8083"

logging:
  level:
    web: debug
    me: debug
    com:
      bjknrt: debug

