apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
configurations:
  - kustomize-config.yaml
resources:
  - ../../base
namespace: dev
images:
  - name: base-image-template
    newName: 192.168.3.201:8080/bjknrt/hmp/user-permission-centre-server
    newTag: $(IMAGE_TAG)
commonLabels:
  app: user-permission-centre
generatorOptions:
  disableNameSuffixHash: true
  labels:
    type: generated
  annotations:
    node: generated
configMapGenerator:
  - name: user-permission-centre-dev-build-env
    envs:
      - ci.env
vars:
  - name: IMAGE_TAG
    objref:
      kind: ConfigMap
      name: user-permission-centre-dev-build-env
      apiVersion: v1
    fieldref:
      fieldpath: data.IMAGE_TAG
patchesStrategicMerge:
  - patch.yaml