apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
configurations:
  - kustomize-config.yaml
resources:
  - ../../base
namespace: stage
images:
  - name: base-image-template
    newName: 192.168.3.201:8080/bjknrt/hmp/article-service-server
    newTag: $(IMAGE_TAG)
commonLabels:
  app: article-service
generatorOptions:
  disableNameSuffixHash: true
  labels:
    type: generated
  annotations:
    node: generated
configMapGenerator:
  - name: article-service-stage-build-env
    envs:
      - ci.env
vars:
  - name: IMAGE_TAG
    objref:
      kind: ConfigMap
      name: article-service-stage-build-env
      apiVersion: v1
    fieldref:
      fieldpath: data.IMAGE_TAG
patchesStrategicMerge:
  - patch.yaml