apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: article-service
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: article-service
          env:
            - name: APP_PROFILE
              value: dev
            - name: NACOS_SERVER_ADDR
              value: 192.168.3.140:8848,192.168.3.141:8848,192.168.3.142:8848